<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Serval.EnvironmentOracle</AssemblyName>
    <RootNamespace>Serval.EnvironmentOracle</RootNamespace>
    <RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
